### ISSUE TITLE
Links broken on workshops page React Hooks Welcome

### ISSUE THREAD

**Issue by alvarezskinner** [kentcdodds/react-hooks#48]
Not a blocker nor big issue but thought you might want to know. I'm assuming this is not coming from this repo, but though it might be the right place to report it.

On the workshops page, under the video, the links seem to be broken.

![Screenshot 2020-10-04 at 10 54 04](https://user-images.githubusercontent.com/2614497/95012383-f6df7000-062f-11eb-80b7-03433f6082ae.png)

**Comment by kentcdodds** [comment]
Hey Andres,


Thanks for the feedback, appreciate it! We'll get that updated.

Thanks,
Zac

--- original message ---
On October 4, 2020, 5:56 AM EDT notifications@github.com wrote:



Not a blocker nor big issue but thought you might want to know. I'm assuming this is not coming from this repo, but though it might be the right place to report it.

On the workshops page, under the video, the links seem to be broken.


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
