### ISSUE TITLE
Tic tac toe exercise question

### ISSUE THREAD

**Issue by jgarciallamas** [kentcdodds/react-hooks#91]
Hi Kent,

 Working on this exercise, more particularly with the game history extra credit, I've seen that you use a couple of states: history and currentStep, so far so good. 
Question is that when you click on any of the squares or you just restart the game, you are calling both setters: setHistory and setCurrentStep so this would trigger at least one re-render of the component. I assumed that React would re-render twice, but by consoling the component I've seen that only one re-render takes place so I was wondering how React manages this particular situation.

Thanks a lot in advance for your comments.

![image](https://user-images.githubusercontent.com/22444788/98245450-3bcd2e00-1f71-11eb-83d8-29d657c17d9b.png)

**Comment by kentcdodds** [comment]
@jgarciallamas,

This is because React can batch these state updates to avoid multiple re-renders. Because `restart` is called from with React's callstack (because an event is being fired and handled by React), it's able to make this work.

I can go in more depth during [office hours](https://kcd.im/office-hours). Good luck!
